// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJqMufbppiYWWGQX_NN-w13KyZpObvGc',
    appId: '1:96250484214:web:9ce8dc95330453967863d7',
    messagingSenderId: '96250484214',
    projectId: 'smart-med-box-28eb7',
    authDomain: 'smart-med-box-28eb7.firebaseapp.com',
    storageBucket: 'smart-med-box-28eb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJqMufbppiYWWGQX_NN-w13KyZpObvGc',
    appId: '1:96250484214:android:your-android-app-id',
    messagingSenderId: '96250484214',
    projectId: 'smart-med-box-28eb7',
    storageBucket: 'smart-med-box-28eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJqMufbppiYWWGQX_NN-w13KyZpObvGc',
    appId: '1:96250484214:ios:your-ios-app-id',
    messagingSenderId: '96250484214',
    projectId: 'smart-med-box-28eb7',
    storageBucket: 'smart-med-box-28eb7.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.smartMedBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJqMufbppiYWWGQX_NN-w13KyZpObvGc',
    appId: '1:96250484214:ios:your-ios-app-id',
    messagingSenderId: '96250484214',
    projectId: 'smart-med-box-28eb7',
    storageBucket: 'smart-med-box-28eb7.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.smartMedBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJqMufbppiYWWGQX_NN-w13KyZpObvGc',
    appId: '1:96250484214:web:9ce8dc95330453967863d7',
    messagingSenderId: '96250484214',
    projectId: 'smart-med-box-28eb7',
    authDomain: 'smart-med-box-28eb7.firebaseapp.com',
    storageBucket: 'smart-med-box-28eb7.firebasestorage.app',
  );
}